package com.skiwi.bfcompiler.analyzers;

import com.skiwi.bfcompiler.source.SourceFile;
import com.skiwi.bfcompiler.tokens.Token;
import org.junit.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static com.skiwi.bfcompiler.tokens.Token.*;
import static org.junit.Assert.*;

/**
 * @author Frank van Heeswijk
 */
public class LexicalAnalyzerTest {
    @Test
    public void testGetTokens() throws Exception {
        Path file = Paths.get(getClass().getClassLoader().getResource("hello-world.bf").toURI());
        SourceFile sourceFile = new SourceFile(file);
        LexicalAnalyzer lexicalAnalyzer = new LexicalAnalyzer(sourceFile);

        Token[] expectedTokens = { POINTER_RIGHT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, JUMP_PAST, DECREMENT, POINTER_LEFT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, POINTER_RIGHT, JUMP_BACK, POINTER_LEFT, OUTPUT, POINTER_RIGHT, POINTER_RIGHT, INCREMENT, POINTER_RIGHT, DECREMENT, JUMP_PAST, INCREMENT, JUMP_BACK, INCREMENT, INCREMENT, POINTER_RIGHT, INCREMENT, INCREMENT, POINTER_RIGHT, INCREMENT, INCREMENT, INCREMENT, JUMP_PAST, POINTER_RIGHT, JUMP_PAST, DECREMENT, POINTER_RIGHT, INCREMENT, INCREMENT, INCREMENT, POINTER_LEFT, POINTER_LEFT, INCREMENT, INCREMENT, INCREMENT, POINTER_RIGHT, JUMP_BACK, POINTER_LEFT, POINTER_LEFT, JUMP_BACK, POINTER_RIGHT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, OUTPUT, POINTER_RIGHT, DECREMENT, POINTER_RIGHT, INCREMENT, INCREMENT, INCREMENT, OUTPUT, OUTPUT, INCREMENT, INCREMENT, INCREMENT, OUTPUT, POINTER_RIGHT, DECREMENT, OUTPUT, POINTER_LEFT, POINTER_LEFT, INCREMENT, JUMP_PAST, POINTER_RIGHT, JUMP_PAST, INCREMENT, POINTER_RIGHT, INCREMENT, JUMP_BACK, POINTER_RIGHT, POINTER_RIGHT, JUMP_BACK, POINTER_LEFT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, OUTPUT, POINTER_RIGHT, POINTER_RIGHT, OUTPUT, INCREMENT, INCREMENT, INCREMENT, OUTPUT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, OUTPUT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, OUTPUT, POINTER_RIGHT, INCREMENT, OUTPUT, POINTER_RIGHT, INCREMENT, OUTPUT };

        assertArrayEquals(expectedTokens, lexicalAnalyzer.getTokens().toArray());
    }

    @Test
    public void testGetTokensWithIgnored() throws Exception {
        Path file = Paths.get(getClass().getClassLoader().getResource("hello-world-ignored.bf").toURI());
        SourceFile sourceFile = new SourceFile(file);
        LexicalAnalyzer lexicalAnalyzer = new LexicalAnalyzer(sourceFile);

        Token[] expectedTokens = { POINTER_RIGHT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, JUMP_PAST, DECREMENT, POINTER_LEFT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, INCREMENT, POINTER_RIGHT, JUMP_BACK, POINTER_LEFT, OUTPUT, POINTER_RIGHT, POINTER_RIGHT, INCREMENT, POINTER_RIGHT, DECREMENT, JUMP_PAST, INCREMENT, JUMP_BACK, INCREMENT, INCREMENT, POINTER_RIGHT, INCREMENT, INCREMENT, POINTER_RIGHT, INCREMENT, INCREMENT, INCREMENT, JUMP_PAST, POINTER_RIGHT, JUMP_PAST, DECREMENT, POINTER_RIGHT, INCREMENT, INCREMENT, INCREMENT, POINTER_LEFT, POINTER_LEFT, INCREMENT, INCREMENT, INCREMENT, POINTER_RIGHT, JUMP_BACK, POINTER_LEFT, POINTER_LEFT, JUMP_BACK, POINTER_RIGHT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, OUTPUT, POINTER_RIGHT, DECREMENT, POINTER_RIGHT, INCREMENT, INCREMENT, INCREMENT, OUTPUT, OUTPUT, INCREMENT, INCREMENT, INCREMENT, OUTPUT, POINTER_RIGHT, DECREMENT, OUTPUT, POINTER_LEFT, POINTER_LEFT, INCREMENT, JUMP_PAST, POINTER_RIGHT, JUMP_PAST, INCREMENT, POINTER_RIGHT, INCREMENT, JUMP_BACK, POINTER_RIGHT, POINTER_RIGHT, JUMP_BACK, POINTER_LEFT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, OUTPUT, POINTER_RIGHT, POINTER_RIGHT, OUTPUT, INCREMENT, INCREMENT, INCREMENT, OUTPUT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, OUTPUT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, DECREMENT, OUTPUT, POINTER_RIGHT, INCREMENT, OUTPUT, POINTER_RIGHT, INCREMENT, OUTPUT };

        assertArrayEquals(expectedTokens, lexicalAnalyzer.getTokens().toArray());
    }
}