package com.skiwi.bfcompiler.generators;

import com.skiwi.bfcompiler.analyzers.LexicalAnalyzer;
import com.skiwi.bfcompiler.analyzers.SyntaxAnalyzer;
import com.skiwi.bfcompiler.ast.AST;
import com.skiwi.bfcompiler.options.BFOptions;
import com.skiwi.bfcompiler.source.SourceFile;
import org.junit.Test;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static org.junit.Assert.*;

/**
 * @author Frank van Heeswijk
 */
public class TargetCodeGeneratorTest {
    @Test
    public void testGenerateAST() throws Exception {
        Path file = Paths.get(getClass().getClassLoader().getResource("hello-world.bf").toURI());
        SourceFile sourceFile = new SourceFile(file);
        LexicalAnalyzer lexicalAnalyzer = new LexicalAnalyzer(sourceFile);
        SyntaxAnalyzer syntaxAnalyzer = new SyntaxAnalyzer();
        IntermediateCodeGenerator intermediateCodeGenerator = new IntermediateCodeGenerator();
        BFOptions bfOptions = new BFOptions.Builder().memoryCellAmount(30000).build();
        TargetCodeGenerator targetCodeGenerator = new TargetCodeGenerator(bfOptions);

        AST targetAst = targetCodeGenerator.generateAST(intermediateCodeGenerator.generateAST(syntaxAnalyzer.getAST(lexicalAnalyzer.getTokens())));
        List<String> targetAstPrettyPrint = targetAst.prettyPrintStream().collect(Collectors.toList());

        List<String> expectedAstPrettyPrint = Arrays.asList(
            "├── Root",
            "│   ├── Extern",
            "│   │   ├── Function",
            "│   │   │   └── String(_calloc)",
            "│   │   ├── Function",
            "│   │   │   └── String(_fdopen)",
            "│   │   ├── Function",
            "│   │   │   └── String(_fprintf)",
            "│   │   ├── Function",
            "│   │   │   └── String(_getchar)",
            "│   │   └── Function",
            "│   │       └── String(_putchar)",
            "│   ├── DataSection",
            "│   │   ├── DefineByte",
            "│   │   │   ├── Identifier",
            "│   │   │   │   └── String(write_mode)",
            "│   │   │   └── Value",
            "│   │   │       └── ValueList",
            "│   │   │           ├── String(w)",
            "│   │   │           └── Integer(0)",
            "│   │   └── DefineByte",
            "│   │       ├── Identifier",
            "│   │       │   └── String(error_outofmemory)",
            "│   │       └── Value",
            "│   │           └── ValueList",
            "│   │               ├── String(Fatal: The Operating System does not have enough memory available.)",
            "│   │               └── Integer(0)",
            "│   ├── BssSection",
            "│   │   └── ReserveDouble",
            "│   │       ├── Identifier",
            "│   │       │   └── String(bf_memory)",
            "│   │       └── Value",
            "│   │           └── Integer(1)",
            "│   └── TextSection",
            "│       ├── Global",
            "│       │   └── Label",
            "│       │       └── String(_main)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(_main)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EBP)",
            "│       │   └── Operand",
            "│       │       └── Register(ESP)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Dword",
            "│       │           └── Integer(1)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Dword",
            "│       │           └── Integer(30000)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_calloc)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(8)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EAX)",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Jz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(error_exit_outofmemory)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Identifier",
            "│       │   │           └── String(bf_memory)",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_end_9)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_start_9)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jnz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_start_9)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_end_9)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_end_17)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_start_17)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jnz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_start_17)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_end_17)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_end_27)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_start_27)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_end_27_1)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_start_27_1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jnz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_start_27_1)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_end_27_1)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jnz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_start_27)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_end_27)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_end_53)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_start_53)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_end_53_1)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_start_53_1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jnz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_start_53_1)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_end_53_1)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Test",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Jnz",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(loop_start_53)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(loop_end_53)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── Integer(1)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── MemoryAddress",
            "│       │   │       └── Register(EDI)",
            "│       │   └── Operand",
            "│       │       └── Register(AL)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(AL)",
            "│       │   └── Operand",
            "│       │       └── MemoryAddress",
            "│       │           └── Register(EDI)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_putchar)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(4)",
            "│       ├── Jmp",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(normal_exit)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(error_exit_outofmemory)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Identifier",
            "│       │           └── String(write_mode)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Dword",
            "│       │           └── Integer(2)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_fdopen)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(8)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Identifier",
            "│       │           └── String(error_outofmemory)",
            "│       ├── Push",
            "│       │   └── Operand",
            "│       │       └── Register(EAX)",
            "│       ├── Call",
            "│       │   └── Operand",
            "│       │       └── Function",
            "│       │           └── String(_fprintf)",
            "│       ├── Add",
            "│       │   ├── Operand",
            "│       │   │   └── Register(ESP)",
            "│       │   └── Operand",
            "│       │       └── Integer(8)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EAX)",
            "│       │   └── Operand",
            "│       │       └── Integer(-1)",
            "│       ├── JmpShort",
            "│       │   └── Operand",
            "│       │       └── Label",
            "│       │           └── String(exit)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(normal_exit)",
            "│       ├── Mov",
            "│       │   ├── Operand",
            "│       │   │   └── Register(EAX)",
            "│       │   └── Operand",
            "│       │       └── Integer(0)",
            "│       ├── DefineLabel",
            "│       │   └── Label",
            "│       │       └── String(exit)",
            "│       └── Ret"
        );

        assertEquals(expectedAstPrettyPrint, targetAstPrettyPrint);
    }
}